<nav>
    <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="">
            <a href="" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <img src="images/img.jpg" alt="">John Doe
                <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li><a href="<?= $this->url('home') ?>"> Profile</a></li>
                <li>
                    <a href="<?= $this->url('settings') ?>">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                    </a>
                </li>
                <!--<li><a href="">Help</a></li>-->
                <li><a href="<?= $this->url('logout') ?>"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
            </ul>
        </li>
        <li role="presentation" class="dropdown">
            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-envelope-o"></i>
                <span class="badge bg-green">6</span>
            </a>
            <!--activate this if we have alerts-->
            <?php //echo $this->partial("layout.gentelella/navigation/alerts.phtml"); ?>
        </li>
    </ul>
</nav>