<!--member-admin page-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <?= $this->partial('layout.gentelella/head/default.phtml'); ?>
    </head>
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Nursing Essayz</span></a>
                        </div>
                        <div class="clearfix"></div>
                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Welcome,</span>
                                <h2>John Doe</h2>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <!-- /menu profile quick info -->
                        <br />
                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <?= $this->partial("layout.gentelella/sidebar-menu/general.phtml"); ?>
                            </div>
                            <div class="menu_section">
                                <?= $this->partial("layout.gentelella/sidebar-menu/live-on.phtml"); ?>
                            </div>
                        </div>
                        <!-- /sidebar menu -->
                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <?= $this->partial("layout.gentelella/footer/side-bar-footer.phtml"); ?>
                        </div>
                        <!-- /menu footer buttons -->
                    </div>
                </div>
                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <?= $this->partial("layout.gentelella/navigation/masthead.phtml"); ?>
                    </div>
                </div>
                <!-- /top navigation -->
                <!-- page content -->
                <div class="right_col" role="main">
                    <!--flash messages-->
                    <div class=""><?= $this->partial('helper/partial/flash-messenger.phtml'); ?></div>
                    <!--actual content to display to user-->
                    <?= $this->content; ?>
                </div>
                <!-- /page content -->
                <!-- footer content -->
                <footer>
                    <?php echo $this->partial('layout.gentelella/footer/admin-footer.phtml'); ?>
                </footer>
                <!-- /footer content -->
            </div>
        </div>
        <?= $this->partial('layout.gentelella/scripts/admin-super.phtml'); ?>
    </body>
</html>