<!--minima layout-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <?= $this->partial('layout/head/default'); ?>
    </head>
    <body class="bg-default">
        <div id="content-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <div class="col-sm-12 vertical-tab-lg"></div>
                        <p class="text-center"><a href="/"><img src="/images/logo.png"></a></p>
                    </div>
                </div>
            </div>
            <?= $this->content; ?>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-md-4 col-md-offset-4">
                            <h5 class="text-center text-primary" >
<!--<a href="<?php //$this->siteUrl('/');     ?>" class="">About</a> |-->
<!--<a href="<?php //$this->siteUrl('/help');     ?>" class="">Help</a> |-->
<!--<a href="<?php //$this->siteUrl('/legal/terms-of-service');     ?>" class="">Terms</a>-->
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>