<div class='container footer'>
    <div class="row">
        <div class="col-xs-12 vertical-tab-sm"></div>
    </div>
    <div class='row'>
        <div class='col-md-10 col-md-offset-1'>
            <div class='col-md-4'>
                <ul class='nav nav-stacked'>
                    <li class='list-header'>Our home</li>
                    <li><p class='text-left'>4th Floor, Bishop Magua Centre <br>
                            Ng'ong Road Opp. Uchumi Hyper <br>
                            Nairobi, Kenya. </p></li>
                </ul>
            </div>
            <div class='col-md-2'>
                <ul class='nav nav-stacked'>
                    <li class='list-header'>Our contact</li>
                    <li><a href="#" class="place-mail">info ( at ) nursingessayz dot com</a></li>
                    <li>+254 739-555-719</li>
                </ul>
            </div>
            <div class='col-md-2 col-md-offset-1'>
                <ul class='nav nav-stacked'>
                    <li class='list-header'>Our resources</li>
                    <li><a href="<?= $this->siteUrl('/help'); ?>">Help Section</a></li>
                    <li><a href="<?= $this->siteUrl('/legal/terms-of-service'); ?>">Terms of Service</a></li>
                    <li><a href="<?= $this->siteUrl('/legal/privacy-policy'); ?>">Privacy Policy</a></li>
                </ul>
            </div>
            <div class='col-md-2 col-md-offset-1'>
                <ul class='nav nav-stacked'>
                    <li class='list-header'>Our social scene</li>
                    <li><a href='https://www.facebook.com/nursingessayz' target="_blank">Facebook</a></li>
                    <li><a href='https://twitter.com/nursingessayz' target="_blank">Twitter</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class='row'>
        <hr>
    </div>
    <div class='row'>
        <div class="col-sm-10 col-sm-offset-1">
            <div class='col-sm-4 col-sm-pull-1'>
                <p class="text-center-xs">
                    &COPY; <?php
                    // name of the site
                    $siteName    = "Nursing Essayz";
                    // year you launched the app
                    $launchYear  = 2017;
                    // track the current year
                    $currentYear = date("Y");
                    if ($currentYear == $launchYear) {
                        echo $launchYear . " " . $siteName;
                    } else {
                        echo $launchYear . " - " . $currentYear . " " . $siteName;
                    }
                    ?>  </p>
            </div>
            <div class='col-sm-6 col-sm-offset-2 col-md-4 col-md-offset-4'>
                <p class='text-right text-center-xs'></p>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="vertical-tab-sm visible-xs"></div>
    <div class="vertical-tab-sm"></div>
</div>
