<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nursing Essays</title>
<!-- Bootstrap -->
<link href="/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="/dist/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="/dist/nprogress/nprogress.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="/dist/css/custom.min.css" rel="stylesheet">
<base href="/">