<script src="/dist/scripts/vendor.js"></script>
<script src="/dist/scripts/app.js"></script>
<!-- jQuery -->
<script src="/dist/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="/dist/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/dist/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="/dist/nprogress/nprogress.js"></script>
<!-- Custom Theme Scripts -->
<script src="/dist/js/custom.min.js"></script>